import pandas
import pandas as pd
get_ipython().system('ls')
foo = pd.read_csv("^DJI.csv")
foo.head()
foo['Date']
foo.head()
import matplotlib.pyplot as plt
plt.close('all')
import numpy as np
df = foo
df.plot(x='Date',y='Close')
plt.show()
df.plot.line(x='Date',y='Close')
plt.show()
plt.close('all')
df.plot.line(x='Date',y='Close')
plt.show()
plt.close('all')
data = pd.read_csv("^DJI.csv")
data.set_index(['date'],inplace=True)
data.set_index(['Date'],inplace=True)
data.plot()
plt.show()
plt.close('all')
data.plot(y='Close')
plt.show()
plt.close('all')
data['Date']
data.head()
df['Date']
df.time = pd.to_datetime(data['Date'], format='%Y-%m-%d')
df.time = pd.to_datetime(df['Date'], format='%Y-%m-%d')
df.Date = pd.to_datetime(df['Date'], format='%Y-%m-%d')
df.head()
df['Date']
df.plot()
df.plot(x='Date',y='Close')
plt.show()
df.plot.scatter(x='Date',y='Close')
df.plot.line(x='Date',y='Close')
df.plot.bar(x='Date',y='Close')
plt.show()
plt.close('all')
df.plot.bar(x='Date',y='Close')
plt.show(); plt.close('all')
df.plot.line(x='Date',y='Close')
plt.show(); plt.close('all')
df.plot.bar(x='Date',y='Close')
plt.show(); plt.close('all')
df.plot.line(x='Date',y='Close')
plt.show(); plt.close('all')
df.head()
df.head(30)
df.tail(30)
plt.show(); plt.close('all')
plt.show(); plt.close('all')
df.plot.line(x='Date',y='Close')
plt.show(); plt.close('all')
df['diffClose1'] = df['Close'] - df['Close'].shift(-1)
df.tail(30)
df['diffClose2'] = df['Close'].shift(-1) - df['Close']
df.tail(30)
df['diffClose3'] = df['Close'] - df['Close'].shift(1)
df.tail(30)
del df['diffClose1']
del df['diffClose2']
df.tail(30)
df['percentDiff'] = df['diffClose3'] / df['Close'].shift(1) * 100
df.tail(30)
df.plot.line(x='Date',y='Close')
plt.show(); plt.close('all')
print(In)
print(set(In))
print(len(In))
print(len(set(In)))
print(len(set(In)))
plt.show()
print(len(set(In)))
print(len(In))
print(len(set(In)))
print(set(In))
print(list(set(In)))
print(len(list(set(In))))
for s in list(set(In)):
    print(s)

for s in list(In):
    print(s)
